### ISSUE TITLE
no push notification since iOS update to 15.0

### ISSUE THREAD

**Issue by onefreeworld** [tigase/siskin-im#143]
Hi there,

since the iphone iOS update to 15.0 I don't get push notifications anymore.
as soon as I open the app the messages refresh and so far I didn't miss any messages, but I do not get any notifications when the massages arrive.
Short after new iOS I had to reinstall all apps, so Siskin should be up to date.

I use an iphone SE2020 (and an older apple watch). siskin-im is on 6.4 and iOS already on 15.0.1

no push notifications either if my own windows gajim is turned on or not (on gajim push notification works fine)
issue occurs with every connected contact (all on omemo), my contacts use androids conversation and/or windows gajim

please let me know if there is anything else you need to know and if I missed an already existing issue thread (please link)

any helpful advise is welcome and appreciated.
thank you!

**Comment by licaon-kter** [comment]
Gajim doesn't use Push iirc

There were some push server issues these last 2 days, but should be fixed already.

**Comment by onefreeworld** [comment]
Hi guys,
thanks!
Like always... simply ask and issue is gone. magic :D 

Seems to work a lot better now. Still does not explain why I had the issue for two weeks or something. But well, works now and this is all I need :)
