### ISSUE TITLE
Message from address not in contacts not showing.

### ISSUE THREAD

**Issue by jelbana** [tigase/siskin-im#146]
**Describe the bug**

I get a notification that I received a message from Siskin. The message is from a contact not in my roster. The message displays in both Dino and Conversations, but is no where in my chats. For full disclosure, I am using jmp.chat. SMS messages get delivered from +phonenumber@cheogram.com and are not necessarily already in my contact list. These messages do not get displayed.

**Details (please complete the following information):**
 - Siskin Version: 7.0 (6)
 - iOS version 15.0.1
 - iPhone model: 6s

**Comment by jelbana** [comment]
> "1" on red background on "settings" means that one of the accounts is not connected due to an error or is still connecting. With that you will not receive messages from this account.

Thanks for clarifying. That seems to occur almost every time I open Siskin.

I can also just reconfirm that the same behavior reoccurred with receiving a notification from Siskin of a new message. This message came from a  +phonenumber@cheogram.com, and so was not in my contact list. Upon opening Siskin, the message is nowhere to be be found in the chats screen.

**Comment by jelbana** [comment]
> Do you have message archiving enabled?

Yes, it is enabled.

**Comment by hantu85** [comment]
@jelbana Could you check if `Settings` > `Notifications` > `Notifications from unknown` is enabled?

**Comment by hantu85** [comment]
I have an idea what could cause issues related to messages visible in push notifications but not in the app and I suppose those are fixed already in version 7.0 which is being tested in TestFlight.

**Comment by jelbana** [comment]
I'm on the latest testflight version (build 10), and I still have the same issue as previously described. I get notifications but don't see messages in app that are from addresses like this:

#####;phone-context=ca-us.phone-context.soprani.ca@cheogram.com

**Comment by jelbana** [comment]
I also wanted to add that it still does not work for some +number@cheogram.com messages that are not in my contact list. I thought that it was resolved as some messages were going through, but I now realize that not all are.
